mutation setRiskCedentInfo(
  $idSubscription: ID!
  $column: String!
  $data: String!
) {
  setRiskCedentInfo(
    idSubscription: $idSubscription
    column: $column
    data: $data
  ) {
    statusCode
    message
    error
    response
  }
}
