mutation setNetPremiumUsd($id_subscription: Int, $column: String, $data: String) {
  setNetPremiumUsd(id_subscription: $id_subscription, column: $column, data: $data) {
    statusCode
    message
    response
    error
  }
}
